package com.jinlan.moreornplants.datagen;

import com.jinlan.moreornplants.MoreOrnPlants;
import com.jinlan.moreornplants.block.ModBlocks;
import com.jinlan.moreornplants.util.ModTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.common.data.BlockTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagGenerator extends BlockTagsProvider {
    public ModBlockTagGenerator(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, MoreOrnPlants.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider pProvider) {
        this.tag(BlockTags.FLOWER_POTS)
                .add(ModBlocks.POTTED_RED_MEI_SAPLING.get())
                .add(ModBlocks.POTTED_WHITE_MEI_SAPLING.get())
                .add(ModBlocks.POTTED_GREEN_CALYX_MEI_SAPLING.get())
                .add(ModBlocks.POTTED_DOUBLE_PINK_MEI_SAPLING.get())
                .add(ModBlocks.POTTED_VERSICOLOR_MEI_SAPLING.get())
                .add(ModBlocks.POTTED_RED_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.POTTED_WHITE_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.POTTED_GREEN_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.POTTED_PINK_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.POTTED_VERSICOLOR_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.POTTED_UPRIGHT_CRABAPPLE_SAPLING.get())
                .add(ModBlocks.POTTED_WEEPING_CRABAPPLE_SAPLING.get())
                .add(ModBlocks.POTTED_PINK_APRICOT_SAPLING.get())
                .add(ModBlocks.POTTED_WHITE_APRICOT_SAPLING.get())
                .add(ModBlocks.POTTED_ORNAMENTAL_PEACH_SAPLING.get())
                .add(ModBlocks.POTTED_WILD_PEACH_SAPLING.get())
                .add(ModBlocks.POTTED_PEAR_SAPLING.get())
                .add(ModBlocks.POTTED_FLOWERING_PURPLE_LEAF_PLUM_SAPLING.get())
                .add(ModBlocks.POTTED_PURPLE_LEAF_PLUM_SAPLING.get())
                .add(ModBlocks.POTTED_GOLDEN_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.POTTED_ORANGE_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.POTTED_WHITE_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.POTTED_GOLDEN_GINKGO_SAPLING.get())
                .add(ModBlocks.POTTED_GREEN_GINKGO_SAPLING.get())
                .add(ModBlocks.POTTED_WINTERSWEET_BUSH.get())
                .add(ModBlocks.POTTED_CHRYSANTHEMUM.get())
                .add(ModBlocks.POTTED_GOLDEN_CHRYSANTHEMUM.get())
                .add(ModBlocks.POTTED_GOLD_BACKED_SCARLET_MUM.get())
                .add(ModBlocks.POTTED_WHITE_CHRYSANTHEMUM.get())
                .add(ModBlocks.POTTED_GREEN_CHRYSANTHEMUM.get())
                .add(ModBlocks.POTTED_PURPLE_CHRYSANTHEMUM.get())
                .add(ModBlocks.POTTED_VIOLET_PINK_CHRYSANTHEMUM.get())
                .add(ModBlocks.POTTED_PINK_CHRYSANTHEMUM.get())
                .add(ModBlocks.POTTED_LIGHT_PINK_CHRYSANTHEMUM.get())
                .add(ModBlocks.POTTED_SPRING_CYMBIDIUM.get())
                .add(ModBlocks.POTTED_PEONY.get())
                .add(ModBlocks.POTTED_LIGHT_PINK_PEONY.get())
                .add(ModBlocks.POTTED_VIOLET_PINK_PEONY.get())
                .add(ModBlocks.POTTED_PINK_PEONY.get())
                .add(ModBlocks.POTTED_RED_PEONY.get())
                .add(ModBlocks.POTTED_LIGHT_RED_PEONY.get())
                .add(ModBlocks.POTTED_INK_RED_PEONY.get())
                .add(ModBlocks.POTTED_VERMILION_PEONY.get())
                .add(ModBlocks.POTTED_PURPLE_PEONY.get())
                .add(ModBlocks.POTTED_LIGHT_PURPLE_PEONY.get())
                .add(ModBlocks.POTTED_INK_PURPLE_PEONY.get())
                .add(ModBlocks.POTTED_VIOLET_PEONY.get())
                .add(ModBlocks.POTTED_YELLOW_PEONY.get())
                .add(ModBlocks.POTTED_LIGHT_YELLOW_PEONY.get())
                .add(ModBlocks.POTTED_OCHRE_YELLOW_PEONY.get())
                .add(ModBlocks.POTTED_GOLDEN_PEONY.get())
                .add(ModBlocks.POTTED_WHITE_PEONY.get())
                .add(ModBlocks.POTTED_INK_PEONY.get())
                .add(ModBlocks.POTTED_BLUE_PEONY.get())
                .add(ModBlocks.POTTED_GREEN_PEONY.get())
                .add(ModBlocks.POTTED_COLORFUL_PEONY.get())
                .add(ModBlocks.POTTED_LIGHT_COLORFUL_PEONY.get())
                .add(ModBlocks.POTTED_INK_COLORFUL_PEONY.get())
                .add(ModBlocks.POTTED_RED_WHITE_PEONY.get())
                .add(ModBlocks.POTTED_PINK_WHITE_PEONY.get())
                .add(ModBlocks.POTTED_YELLOW_WHITE_PEONY.get())
                .add(ModBlocks.POTTED_PURPLE_WHITE_PEONY.get())
                .add(ModBlocks.POTTED_WU_HUA_LONG_YU_PEONY.get())
                .add(ModBlocks.POTTED_MAUVE_PEONY.get())
                .add(ModBlocks.POTTED_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.POTTED_PINK_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.POTTED_YELLOW_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.POTTED_WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.POTTED_RED_PINK_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.POTTED_RED_YELLOW_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.POTTED_RED_WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.POTTED_PINK_WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.POTTED_YELLOW_WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.POTTED_CAMELLIA.get())
                .add(ModBlocks.POTTED_PINK_CAMELLIA.get())
                .add(ModBlocks.POTTED_WHITE_CAMELLIA.get())
                .add(ModBlocks.POTTED_VERSICOLOR_CAMELLIA.get())
                .add(ModBlocks.POTTED_CRIMSON_AZALEA.get());

        this.tag(BlockTags.FLOWERS)
                .addTag(BlockTags.SMALL_FLOWERS)
                .addTag(BlockTags.TALL_FLOWERS)
                .add(ModBlocks.RED_MEI_LEAVES.get())
                .add(ModBlocks.WHITE_MEI_LEAVES.get())
                .add(ModBlocks.GREEN_CALYX_MEI_LEAVES.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_LEAVES.get())
                .add(ModBlocks.VERSICOLOR_MEI_LEAVES.get())
                .add(ModBlocks.RED_WEEPING_MEI.get())
                .add(ModBlocks.RED_WEEPING_MEI_PLANT.get())
                .add(ModBlocks.WHITE_WEEPING_MEI.get())
                .add(ModBlocks.WHITE_WEEPING_MEI_PLANT.get())
                .add(ModBlocks.GREEN_WEEPING_MEI.get())
                .add(ModBlocks.GREEN_WEEPING_MEI_PLANT.get())
                .add(ModBlocks.PINK_WEEPING_MEI.get())
                .add(ModBlocks.PINK_WEEPING_MEI_PLANT.get())
                .add(ModBlocks.VERSICOLOR_WEEPING_MEI.get())
                .add(ModBlocks.VERSICOLOR_WEEPING_MEI_PLANT.get())
                .add(ModBlocks.UPRIGHT_CRABAPPLE_LEAVES.get())
                .add(ModBlocks.WEEPING_CRABAPPLE_LEAVES.get())
                .add(ModBlocks.WEEPING_CRABAPPLE.get())
                .add(ModBlocks.PINK_APRICOT_LEAVES.get())
                .add(ModBlocks.WHITE_APRICOT_LEAVES.get())
                .add(ModBlocks.ORNAMENTAL_PEACH_LEAVES.get())
                .add(ModBlocks.WILD_PEACH_LEAVES.get())
                .add(ModBlocks.PEAR_LEAVES.get())
                .add(ModBlocks.FLOWERING_PURPLE_LEAF_PLUM_LEAVES.get())
                .add(ModBlocks.GOLDEN_OSMANTHUS_LEAVES.get())
                .add(ModBlocks.ORANGE_OSMANTHUS_LEAVES.get())
                .add(ModBlocks.WHITE_OSMANTHUS_LEAVES.get())
                .add(ModBlocks.PEACH_PINK_PETALS.get());

        this.tag(BlockTags.LEAVES)
                .add(ModBlocks.RED_MEI_LEAVES.get())
                .add(ModBlocks.WHITE_MEI_LEAVES.get())
                .add(ModBlocks.GREEN_CALYX_MEI_LEAVES.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_LEAVES.get())
                .add(ModBlocks.VERSICOLOR_MEI_LEAVES.get())
                .add(ModBlocks.UPRIGHT_CRABAPPLE_LEAVES.get())
                .add(ModBlocks.WEEPING_CRABAPPLE_LEAVES.get())
                .add(ModBlocks.PINK_APRICOT_LEAVES.get())
                .add(ModBlocks.WHITE_APRICOT_LEAVES.get())
                .add(ModBlocks.ORNAMENTAL_PEACH_LEAVES.get())
                .add(ModBlocks.WILD_PEACH_LEAVES.get())
                .add(ModBlocks.PEAR_LEAVES.get())
                .add(ModBlocks.FLOWERING_PURPLE_LEAF_PLUM_LEAVES.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_LEAVES.get())
                .add(ModBlocks.GOLDEN_OSMANTHUS_LEAVES.get())
                .add(ModBlocks.ORANGE_OSMANTHUS_LEAVES.get())
                .add(ModBlocks.WHITE_OSMANTHUS_LEAVES.get())
                .add(ModBlocks.GOLDEN_GINKGO_LEAVES.get())
                .add(ModBlocks.GREEN_GINKGO_LEAVES.get())
                .add(ModBlocks.YELLOW_CHINESE_PARASOL_LEAVES.get())
                .add(ModBlocks.GREEN_CHINESE_PARASOL_LEAVES.get())
                .add(ModBlocks.SWEETGUM_LEAVES.get())
                .add(ModBlocks.CAMPHOR_LEAVES.get())
                .add(ModBlocks.NEW_CAMPHOR_LEAVES.get());

        this.tag(BlockTags.LOGS_THAT_BURN)
                .addTag(ModTags.Blocks.RED_MEI_LOGS)
                .addTag(ModTags.Blocks.WHITE_MEI_LOGS)
                .addTag(ModTags.Blocks.GREEN_CALYX_MEI_LOGS)
                .addTag(ModTags.Blocks.DOUBLE_PINK_MEI_LOGS)
                .addTag(ModTags.Blocks.CRABAPPLE_LOGS)
                .addTag(ModTags.Blocks.APRICOT_LOGS)
                .addTag(ModTags.Blocks.PEACH_LOGS)
                .addTag(ModTags.Blocks.PEAR_LOGS)
                .addTag(ModTags.Blocks.PURPLE_LEAF_PLUM_LOGS)
                .addTag(ModTags.Blocks.OSMANTHUS_LOGS)
                .addTag(ModTags.Blocks.GINKGO_LOGS)
                .addTag(ModTags.Blocks.CHINESE_PARASOL_LOGS)
                .addTag(ModTags.Blocks.SWEETGUM_LOGS)
                .addTag(ModTags.Blocks.CAMPHOR_LOGS);

        this.tag(BlockTags.PLANKS)
                .add(ModBlocks.RED_MEI_PLANKS.get())
                .add(ModBlocks.WHITE_MEI_PLANKS.get())
                .add(ModBlocks.GREEN_CALYX_MEI_PLANKS.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_PLANKS.get())
                .add(ModBlocks.CRABAPPLE_PLANKS.get())
                .add(ModBlocks.APRICOT_PLANKS.get())
                .add(ModBlocks.PEACH_PLANKS.get())
                .add(ModBlocks.PEAR_PLANKS.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_PLANKS.get())
                .add(ModBlocks.OSMANTHUS_PLANKS.get())
                .add(ModBlocks.GINKGO_PLANKS.get())
                .add(ModBlocks.CHINESE_PARASOL_PLANKS.get())
                .add(ModBlocks.SWEETGUM_PLANKS.get())
                .add(ModBlocks.CAMPHOR_PLANKS.get());

        this.tag(BlockTags.WOODEN_STAIRS)
                .add(ModBlocks.RED_MEI_STAIRS.get())
                .add(ModBlocks.WHITE_MEI_STAIRS.get())
                .add(ModBlocks.GREEN_CALYX_MEI_STAIRS.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_STAIRS.get())
                .add(ModBlocks.CRABAPPLE_STAIRS.get())
                .add(ModBlocks.APRICOT_STAIRS.get())
                .add(ModBlocks.PEACH_STAIRS.get())
                .add(ModBlocks.PEAR_STAIRS.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_STAIRS.get())
                .add(ModBlocks.OSMANTHUS_STAIRS.get())
                .add(ModBlocks.GINKGO_STAIRS.get())
                .add(ModBlocks.CHINESE_PARASOL_STAIRS.get())
                .add(ModBlocks.SWEETGUM_STAIRS.get())
                .add(ModBlocks.CAMPHOR_STAIRS.get());

        this.tag(BlockTags.WOODEN_SLABS)
                .add(ModBlocks.RED_MEI_SLAB.get())
                .add(ModBlocks.WHITE_MEI_SLAB.get())
                .add(ModBlocks.GREEN_CALYX_MEI_SLAB.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_SLAB.get())
                .add(ModBlocks.CRABAPPLE_SLAB.get())
                .add(ModBlocks.APRICOT_SLAB.get())
                .add(ModBlocks.PEACH_SLAB.get())
                .add(ModBlocks.PEAR_SLAB.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_SLAB.get())
                .add(ModBlocks.OSMANTHUS_SLAB.get())
                .add(ModBlocks.GINKGO_SLAB.get())
                .add(ModBlocks.CHINESE_PARASOL_SLAB.get())
                .add(ModBlocks.SWEETGUM_SLAB.get())
                .add(ModBlocks.CAMPHOR_SLAB.get());

        this.tag(BlockTags.WOODEN_BUTTONS)
                .add(ModBlocks.RED_MEI_BUTTON.get())
                .add(ModBlocks.WHITE_MEI_BUTTON.get())
                .add(ModBlocks.GREEN_CALYX_MEI_BUTTON.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_BUTTON.get())
                .add(ModBlocks.CRABAPPLE_BUTTON.get())
                .add(ModBlocks.APRICOT_BUTTON.get())
                .add(ModBlocks.PEACH_BUTTON.get())
                .add(ModBlocks.PEAR_BUTTON.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_BUTTON.get())
                .add(ModBlocks.OSMANTHUS_BUTTON.get())
                .add(ModBlocks.GINKGO_BUTTON.get())
                .add(ModBlocks.CHINESE_PARASOL_BUTTON.get())
                .add(ModBlocks.SWEETGUM_BUTTON.get())
                .add(ModBlocks.CAMPHOR_BUTTON.get());

        this.tag(BlockTags.WOODEN_PRESSURE_PLATES)
                .add(ModBlocks.RED_MEI_PRESSURE_PLATE.get())
                .add(ModBlocks.WHITE_MEI_PRESSURE_PLATE.get())
                .add(ModBlocks.GREEN_CALYX_MEI_PRESSURE_PLATE.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_PRESSURE_PLATE.get())
                .add(ModBlocks.CRABAPPLE_PRESSURE_PLATE.get())
                .add(ModBlocks.APRICOT_PRESSURE_PLATE.get())
                .add(ModBlocks.PEACH_PRESSURE_PLATE.get())
                .add(ModBlocks.PEAR_PRESSURE_PLATE.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_PRESSURE_PLATE.get())
                .add(ModBlocks.OSMANTHUS_PRESSURE_PLATE.get())
                .add(ModBlocks.GINKGO_PRESSURE_PLATE.get())
                .add(ModBlocks.CHINESE_PARASOL_PRESSURE_PLATE.get())
                .add(ModBlocks.SWEETGUM_PRESSURE_PLATE.get())
                .add(ModBlocks.CAMPHOR_PRESSURE_PLATE.get());

        this.tag(BlockTags.WOODEN_FENCES)
                .add(ModBlocks.RED_MEI_FENCE.get())
                .add(ModBlocks.WHITE_MEI_FENCE.get())
                .add(ModBlocks.GREEN_CALYX_MEI_FENCE.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_FENCE.get())
                .add(ModBlocks.CRABAPPLE_FENCE.get())
                .add(ModBlocks.APRICOT_FENCE.get())
                .add(ModBlocks.PEACH_FENCE.get())
                .add(ModBlocks.PEAR_FENCE.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_FENCE.get())
                .add(ModBlocks.OSMANTHUS_FENCE.get())
                .add(ModBlocks.GINKGO_FENCE.get())
                .add(ModBlocks.CHINESE_PARASOL_FENCE.get())
                .add(ModBlocks.SWEETGUM_FENCE.get())
                .add(ModBlocks.CAMPHOR_FENCE.get());

        this.tag(BlockTags.FENCE_GATES)
                .add(ModBlocks.RED_MEI_FENCE_GATE.get())
                .add(ModBlocks.WHITE_MEI_FENCE_GATE.get())
                .add(ModBlocks.GREEN_CALYX_MEI_FENCE_GATE.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_FENCE_GATE.get())
                .add(ModBlocks.CRABAPPLE_FENCE_GATE.get())
                .add(ModBlocks.APRICOT_FENCE_GATE.get())
                .add(ModBlocks.PEACH_FENCE_GATE.get())
                .add(ModBlocks.PEAR_FENCE_GATE.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_FENCE_GATE.get())
                .add(ModBlocks.OSMANTHUS_FENCE_GATE.get())
                .add(ModBlocks.GINKGO_FENCE_GATE.get())
                .add(ModBlocks.CHINESE_PARASOL_FENCE_GATE.get())
                .add(ModBlocks.SWEETGUM_FENCE_GATE.get())
                .add(ModBlocks.CAMPHOR_FENCE_GATE.get());

        this.tag(BlockTags.WOODEN_DOORS)
                .add(ModBlocks.RED_MEI_DOOR.get())
                .add(ModBlocks.WHITE_MEI_DOOR.get())
                .add(ModBlocks.GREEN_CALYX_MEI_DOOR.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_DOOR.get())
                .add(ModBlocks.CRABAPPLE_DOOR.get())
                .add(ModBlocks.APRICOT_DOOR.get())
                .add(ModBlocks.PEACH_DOOR.get())
                .add(ModBlocks.PEAR_DOOR.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_DOOR.get())
                .add(ModBlocks.OSMANTHUS_DOOR.get())
                .add(ModBlocks.GINKGO_DOOR.get())
                .add(ModBlocks.CHINESE_PARASOL_DOOR.get())
                .add(ModBlocks.SWEETGUM_DOOR.get())
                .add(ModBlocks.CAMPHOR_DOOR.get());

        this.tag(BlockTags.WOODEN_TRAPDOORS)
                .add(ModBlocks.RED_MEI_TRAPDOOR.get())
                .add(ModBlocks.WHITE_MEI_TRAPDOOR.get())
                .add(ModBlocks.GREEN_CALYX_MEI_TRAPDOOR.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_TRAPDOOR.get())
                .add(ModBlocks.CRABAPPLE_TRAPDOOR.get())
                .add(ModBlocks.APRICOT_TRAPDOOR.get())
                .add(ModBlocks.PEACH_TRAPDOOR.get())
                .add(ModBlocks.PEAR_TRAPDOOR.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_TRAPDOOR.get())
                .add(ModBlocks.OSMANTHUS_TRAPDOOR.get())
                .add(ModBlocks.GINKGO_TRAPDOOR.get())
                .add(ModBlocks.CHINESE_PARASOL_TRAPDOOR.get())
                .add(ModBlocks.SWEETGUM_TRAPDOOR.get())
                .add(ModBlocks.CAMPHOR_TRAPDOOR.get());

        this.tag(BlockTags.STANDING_SIGNS)
                .add(ModBlocks.RED_MEI_SIGN.get())
                .add(ModBlocks.WHITE_MEI_SIGN.get())
                .add(ModBlocks.GREEN_CALYX_MEI_SIGN.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_SIGN.get())
                .add(ModBlocks.CRABAPPLE_SIGN.get())
                .add(ModBlocks.APRICOT_SIGN.get())
                .add(ModBlocks.PEACH_SIGN.get())
                .add(ModBlocks.PEAR_SIGN.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_SIGN.get())
                .add(ModBlocks.OSMANTHUS_SIGN.get())
                .add(ModBlocks.GINKGO_SIGN.get())
                .add(ModBlocks.CHINESE_PARASOL_SIGN.get())
                .add(ModBlocks.SWEETGUM_SIGN.get())
                .add(ModBlocks.CAMPHOR_SIGN.get());

        this.tag(BlockTags.WALL_SIGNS)
                .add(ModBlocks.RED_MEI_WALL_SIGN.get())
                .add(ModBlocks.WHITE_MEI_WALL_SIGN.get())
                .add(ModBlocks.GREEN_CALYX_MEI_WALL_SIGN.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_WALL_SIGN.get())
                .add(ModBlocks.CRABAPPLE_WALL_SIGN.get())
                .add(ModBlocks.APRICOT_WALL_SIGN.get())
                .add(ModBlocks.PEACH_WALL_SIGN.get())
                .add(ModBlocks.PEAR_WALL_SIGN.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_WALL_SIGN.get())
                .add(ModBlocks.OSMANTHUS_WALL_SIGN.get())
                .add(ModBlocks.GINKGO_WALL_SIGN.get())
                .add(ModBlocks.CHINESE_PARASOL_WALL_SIGN.get())
                .add(ModBlocks.SWEETGUM_WALL_SIGN.get())
                .add(ModBlocks.CAMPHOR_WALL_SIGN.get());

        this.tag(BlockTags.CEILING_HANGING_SIGNS)
                .add(ModBlocks.RED_MEI_HANGING_SIGN.get())
                .add(ModBlocks.WHITE_MEI_HANGING_SIGN.get())
                .add(ModBlocks.GREEN_CALYX_MEI_HANGING_SIGN.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_HANGING_SIGN.get())
                .add(ModBlocks.CRABAPPLE_HANGING_SIGN.get())
                .add(ModBlocks.APRICOT_HANGING_SIGN.get())
                .add(ModBlocks.PEACH_HANGING_SIGN.get())
                .add(ModBlocks.PEAR_HANGING_SIGN.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_HANGING_SIGN.get())
                .add(ModBlocks.OSMANTHUS_HANGING_SIGN.get())
                .add(ModBlocks.GINKGO_HANGING_SIGN.get())
                .add(ModBlocks.CHINESE_PARASOL_HANGING_SIGN.get())
                .add(ModBlocks.SWEETGUM_HANGING_SIGN.get())
                .add(ModBlocks.CAMPHOR_HANGING_SIGN.get());

        this.tag(BlockTags.WALL_HANGING_SIGNS)
                .add(ModBlocks.RED_MEI_WALL_HANGING_SIGN.get())
                .add(ModBlocks.WHITE_MEI_WALL_HANGING_SIGN.get())
                .add(ModBlocks.GREEN_CALYX_MEI_WALL_HANGING_SIGN.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_WALL_HANGING_SIGN.get())
                .add(ModBlocks.CRABAPPLE_WALL_HANGING_SIGN.get())
                .add(ModBlocks.APRICOT_WALL_HANGING_SIGN.get())
                .add(ModBlocks.PEACH_WALL_HANGING_SIGN.get())
                .add(ModBlocks.PEAR_WALL_HANGING_SIGN.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_WALL_HANGING_SIGN.get())
                .add(ModBlocks.OSMANTHUS_WALL_HANGING_SIGN.get())
                .add(ModBlocks.GINKGO_WALL_HANGING_SIGN.get())
                .add(ModBlocks.CHINESE_PARASOL_WALL_HANGING_SIGN.get())
                .add(ModBlocks.SWEETGUM_WALL_HANGING_SIGN.get())
                .add(ModBlocks.CAMPHOR_WALL_HANGING_SIGN.get());

        this.tag(ModTags.Blocks.RED_MEI_LOGS)
                .add(ModBlocks.RED_MEI_LOG.get(),
                        ModBlocks.RED_MEI_WOOD.get(),
                        ModBlocks.STRIPPED_RED_MEI_LOG.get(),
                        ModBlocks.STRIPPED_RED_MEI_WOOD.get());
        this.tag(ModTags.Blocks.WHITE_MEI_LOGS)
                .add(ModBlocks.WHITE_MEI_LOG.get(),
                        ModBlocks.WHITE_MEI_WOOD.get(),
                        ModBlocks.STRIPPED_WHITE_MEI_LOG.get(),
                        ModBlocks.STRIPPED_WHITE_MEI_WOOD.get());
        this.tag(ModTags.Blocks.GREEN_CALYX_MEI_LOGS)
                .add(ModBlocks.GREEN_CALYX_MEI_LOG.get(),
                        ModBlocks.GREEN_CALYX_MEI_WOOD.get(),
                        ModBlocks.STRIPPED_GREEN_CALYX_MEI_LOG.get(),
                        ModBlocks.STRIPPED_GREEN_CALYX_MEI_WOOD.get());
        this.tag(ModTags.Blocks.DOUBLE_PINK_MEI_LOGS)
                .add(ModBlocks.DOUBLE_PINK_MEI_LOG.get(),
                        ModBlocks.DOUBLE_PINK_MEI_WOOD.get(),
                        ModBlocks.STRIPPED_DOUBLE_PINK_MEI_LOG.get(),
                        ModBlocks.STRIPPED_DOUBLE_PINK_MEI_WOOD.get());
        this.tag(ModTags.Blocks.CRABAPPLE_LOGS)
                .add(ModBlocks.CRABAPPLE_LOG.get(),
                        ModBlocks.CRABAPPLE_WOOD.get(),
                        ModBlocks.STRIPPED_CRABAPPLE_LOG.get(),
                        ModBlocks.STRIPPED_CRABAPPLE_WOOD.get());
        this.tag(ModTags.Blocks.APRICOT_LOGS)
                .add(ModBlocks.APRICOT_LOG.get(),
                        ModBlocks.APRICOT_WOOD.get(),
                        ModBlocks.STRIPPED_APRICOT_LOG.get(),
                        ModBlocks.STRIPPED_APRICOT_WOOD.get());
        this.tag(ModTags.Blocks.PEACH_LOGS)
                .add(ModBlocks.PEACH_LOG.get(),
                        ModBlocks.PEACH_WOOD.get(),
                        ModBlocks.STRIPPED_PEACH_LOG.get(),
                        ModBlocks.STRIPPED_PEACH_WOOD.get());
        this.tag(ModTags.Blocks.PEAR_LOGS)
                .add(ModBlocks.PEAR_LOG.get(),
                        ModBlocks.PEAR_WOOD.get(),
                        ModBlocks.STRIPPED_PEAR_LOG.get(),
                        ModBlocks.STRIPPED_PEAR_WOOD.get());
        this.tag(ModTags.Blocks.PURPLE_LEAF_PLUM_LOGS)
                .add(ModBlocks.PURPLE_LEAF_PLUM_LOG.get(),
                        ModBlocks.PURPLE_LEAF_PLUM_WOOD.get(),
                        ModBlocks.STRIPPED_PURPLE_LEAF_PLUM_LOG.get(),
                        ModBlocks.STRIPPED_PURPLE_LEAF_PLUM_WOOD.get());
        this.tag(ModTags.Blocks.OSMANTHUS_LOGS)
                .add(ModBlocks.OSMANTHUS_LOG.get(),
                        ModBlocks.OSMANTHUS_WOOD.get(),
                        ModBlocks.STRIPPED_OSMANTHUS_LOG.get(),
                        ModBlocks.STRIPPED_OSMANTHUS_WOOD.get());
        this.tag(ModTags.Blocks.GINKGO_LOGS)
                .add(ModBlocks.GINKGO_LOG.get(),
                        ModBlocks.GINKGO_WOOD.get(),
                        ModBlocks.STRIPPED_GINKGO_LOG.get(),
                        ModBlocks.STRIPPED_GINKGO_WOOD.get());
        this.tag(ModTags.Blocks.CHINESE_PARASOL_LOGS)
                .add(ModBlocks.CHINESE_PARASOL_LOG.get(),
                        ModBlocks.CHINESE_PARASOL_WOOD.get(),
                        ModBlocks.STRIPPED_CHINESE_PARASOL_LOG.get(),
                        ModBlocks.STRIPPED_CHINESE_PARASOL_WOOD.get());
        this.tag(ModTags.Blocks.SWEETGUM_LOGS)
                .add(ModBlocks.SWEETGUM_LOG.get(),
                        ModBlocks.SWEETGUM_WOOD.get(),
                        ModBlocks.STRIPPED_SWEETGUM_LOG.get(),
                        ModBlocks.STRIPPED_SWEETGUM_WOOD.get());
        this.tag(ModTags.Blocks.CAMPHOR_LOGS)
                .add(ModBlocks.CAMPHOR_LOG.get(),
                        ModBlocks.CAMPHOR_WOOD.get(),
                        ModBlocks.STRIPPED_CAMPHOR_LOG.get(),
                        ModBlocks.STRIPPED_CAMPHOR_WOOD.get());

        this.tag(BlockTags.SAPLINGS)
                .add(ModBlocks.RED_MEI_SAPLING.get())
                .add(ModBlocks.WHITE_MEI_SAPLING.get())
                .add(ModBlocks.GREEN_CALYX_MEI_SAPLING.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_SAPLING.get())
                .add(ModBlocks.VERSICOLOR_MEI_SAPLING.get())
                .add(ModBlocks.RED_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.WHITE_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.GREEN_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.PINK_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.VERSICOLOR_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.UPRIGHT_CRABAPPLE_SAPLING.get())
                .add(ModBlocks.WEEPING_CRABAPPLE_SAPLING.get())
                .add(ModBlocks.PINK_APRICOT_SAPLING.get())
                .add(ModBlocks.WHITE_APRICOT_SAPLING.get())
                .add(ModBlocks.ORNAMENTAL_PEACH_SAPLING.get())
                .add(ModBlocks.WILD_PEACH_SAPLING.get())
                .add(ModBlocks.PEAR_SAPLING.get())
                .add(ModBlocks.FLOWERING_PURPLE_LEAF_PLUM_SAPLING.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_SAPLING.get())
                .add(ModBlocks.GOLDEN_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.ORANGE_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.WHITE_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.GOLDEN_GINKGO_SAPLING.get())
                .add(ModBlocks.GREEN_GINKGO_SAPLING.get())
                .add(ModBlocks.YELLOW_CHINESE_PARASOL_SAPLING.get())
                .add(ModBlocks.GREEN_CHINESE_PARASOL_SAPLING.get())
                .add(ModBlocks.SWEETGUM_SAPLING.get())
                .add(ModBlocks.CAMPHOR_SAPLING.get());

        this.tag(BlockTags.SMALL_FLOWERS)
                .add(ModBlocks.RED_MEI_SAPLING.get())
                .add(ModBlocks.WHITE_MEI_SAPLING.get())
                .add(ModBlocks.GREEN_CALYX_MEI_SAPLING.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_SAPLING.get())
                .add(ModBlocks.VERSICOLOR_MEI_SAPLING.get())
                .add(ModBlocks.RED_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.WHITE_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.GREEN_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.PINK_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.VERSICOLOR_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.UPRIGHT_CRABAPPLE_SAPLING.get())
                .add(ModBlocks.WEEPING_CRABAPPLE_SAPLING.get())
                .add(ModBlocks.PINK_APRICOT_SAPLING.get())
                .add(ModBlocks.WHITE_APRICOT_SAPLING.get())
                .add(ModBlocks.ORNAMENTAL_PEACH_SAPLING.get())
                .add(ModBlocks.WILD_PEACH_SAPLING.get())
                .add(ModBlocks.PEAR_SAPLING.get())
                .add(ModBlocks.FLOWERING_PURPLE_LEAF_PLUM_SAPLING.get())
                .add(ModBlocks.GOLDEN_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.ORANGE_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.WHITE_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.WINTERSWEET_BUSH.get())
                .add(ModBlocks.CHRYSANTHEMUM.get())
                .add(ModBlocks.GOLDEN_CHRYSANTHEMUM.get())
                .add(ModBlocks.GOLD_BACKED_SCARLET_MUM.get())
                .add(ModBlocks.WHITE_CHRYSANTHEMUM.get())
                .add(ModBlocks.GREEN_CHRYSANTHEMUM.get())
                .add(ModBlocks.PURPLE_CHRYSANTHEMUM.get())
                .add(ModBlocks.VIOLET_PINK_CHRYSANTHEMUM.get())
                .add(ModBlocks.PINK_CHRYSANTHEMUM.get())
                .add(ModBlocks.LIGHT_PINK_CHRYSANTHEMUM.get())
                .add(ModBlocks.SPRING_CYMBIDIUM.get())
                .add(ModBlocks.PEONY.get())
                .add(ModBlocks.LIGHT_PINK_PEONY.get())
                .add(ModBlocks.VIOLET_PINK_PEONY.get())
                .add(ModBlocks.PINK_PEONY.get())
                .add(ModBlocks.RED_PEONY.get())
                .add(ModBlocks.LIGHT_RED_PEONY.get())
                .add(ModBlocks.INK_RED_PEONY.get())
                .add(ModBlocks.VERMILION_PEONY.get())
                .add(ModBlocks.PURPLE_PEONY.get())
                .add(ModBlocks.LIGHT_PURPLE_PEONY.get())
                .add(ModBlocks.INK_PURPLE_PEONY.get())
                .add(ModBlocks.VIOLET_PEONY.get())
                .add(ModBlocks.YELLOW_PEONY.get())
                .add(ModBlocks.LIGHT_YELLOW_PEONY.get())
                .add(ModBlocks.OCHRE_YELLOW_PEONY.get())
                .add(ModBlocks.GOLDEN_PEONY.get())
                .add(ModBlocks.WHITE_PEONY.get())
                .add(ModBlocks.INK_PEONY.get())
                .add(ModBlocks.BLUE_PEONY.get())
                .add(ModBlocks.GREEN_PEONY.get())
                .add(ModBlocks.COLORFUL_PEONY.get())
                .add(ModBlocks.LIGHT_COLORFUL_PEONY.get())
                .add(ModBlocks.INK_COLORFUL_PEONY.get())
                .add(ModBlocks.RED_WHITE_PEONY.get())
                .add(ModBlocks.PINK_WHITE_PEONY.get())
                .add(ModBlocks.YELLOW_WHITE_PEONY.get())
                .add(ModBlocks.PURPLE_WHITE_PEONY.get())
                .add(ModBlocks.WU_HUA_LONG_YU_PEONY.get())
                .add(ModBlocks.MAUVE_PEONY.get())
                .add(ModBlocks.CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.PINK_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.YELLOW_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.RED_PINK_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.RED_YELLOW_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.RED_WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.PINK_WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.YELLOW_WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.CAMELLIA.get())
                .add(ModBlocks.PINK_CAMELLIA.get())
                .add(ModBlocks.WHITE_CAMELLIA.get())
                .add(ModBlocks.VERSICOLOR_CAMELLIA.get())
                .add(ModBlocks.CRIMSON_AZALEA.get());

        this.tag(BlockTags.TALL_FLOWERS)
                .add(ModBlocks.WINTERSWEET.get())
                .add(ModBlocks.TWO_QIAO_PEONY.get())
                .add(ModBlocks.VERSICOLOR_PEONY.get())
                .add(ModBlocks.CHINESE_ROSE.get())
                .add(ModBlocks.PINK_CHINESE_ROSE.get())
                .add(ModBlocks.YELLOW_CHINESE_ROSE.get())
                .add(ModBlocks.WHITE_CHINESE_ROSE.get())
                .add(ModBlocks.RED_PINK_CHINESE_ROSE.get())
                .add(ModBlocks.RED_YELLOW_CHINESE_ROSE.get())
                .add(ModBlocks.RED_WHITE_CHINESE_ROSE.get())
                .add(ModBlocks.PINK_WHITE_CHINESE_ROSE.get())
                .add(ModBlocks.YELLOW_WHITE_CHINESE_ROSE.get());

        this.tag(ModTags.Blocks.MEI_AND_WINTERSWEET)
                .add(ModBlocks.RED_MEI_SAPLING.get())
                .add(ModBlocks.WHITE_MEI_SAPLING.get())
                .add(ModBlocks.GREEN_CALYX_MEI_SAPLING.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_SAPLING.get())
                .add(ModBlocks.VERSICOLOR_MEI_SAPLING.get())
                .add(ModBlocks.RED_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.WHITE_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.GREEN_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.PINK_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.VERSICOLOR_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.WINTERSWEET.get())
                .add(ModBlocks.WINTERSWEET_BUSH.get());

        this.tag(ModTags.Blocks.MEI)
                .add(ModBlocks.RED_MEI_SAPLING.get())
                .add(ModBlocks.WHITE_MEI_SAPLING.get())
                .add(ModBlocks.GREEN_CALYX_MEI_SAPLING.get())
                .add(ModBlocks.DOUBLE_PINK_MEI_SAPLING.get())
                .add(ModBlocks.VERSICOLOR_MEI_SAPLING.get())
                .add(ModBlocks.RED_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.WHITE_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.GREEN_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.PINK_WEEPING_MEI_SAPLING.get())
                .add(ModBlocks.VERSICOLOR_WEEPING_MEI_SAPLING.get());

        this.tag(ModTags.Blocks.TREE_PEONY)
                .add(Blocks.PEONY)
                .add(ModBlocks.TWO_QIAO_PEONY.get())
                .add(ModBlocks.VERSICOLOR_PEONY.get());

        this.tag(ModTags.Blocks.HERBACEOUS_PEONY)
                .add(ModBlocks.PEONY.get())
                .add(ModBlocks.LIGHT_PINK_PEONY.get())
                .add(ModBlocks.VIOLET_PINK_PEONY.get())
                .add(ModBlocks.PINK_PEONY.get())
                .add(ModBlocks.RED_PEONY.get())
                .add(ModBlocks.LIGHT_RED_PEONY.get())
                .add(ModBlocks.INK_RED_PEONY.get())
                .add(ModBlocks.VERMILION_PEONY.get())
                .add(ModBlocks.PURPLE_PEONY.get())
                .add(ModBlocks.LIGHT_PURPLE_PEONY.get())
                .add(ModBlocks.INK_PURPLE_PEONY.get())
                .add(ModBlocks.VIOLET_PEONY.get())
                .add(ModBlocks.YELLOW_PEONY.get())
                .add(ModBlocks.LIGHT_YELLOW_PEONY.get())
                .add(ModBlocks.OCHRE_YELLOW_PEONY.get())
                .add(ModBlocks.GOLDEN_PEONY.get())
                .add(ModBlocks.WHITE_PEONY.get())
                .add(ModBlocks.INK_PEONY.get())
                .add(ModBlocks.BLUE_PEONY.get())
                .add(ModBlocks.GREEN_PEONY.get())
                .add(ModBlocks.COLORFUL_PEONY.get())
                .add(ModBlocks.LIGHT_COLORFUL_PEONY.get())
                .add(ModBlocks.INK_COLORFUL_PEONY.get())
                .add(ModBlocks.RED_WHITE_PEONY.get())
                .add(ModBlocks.PINK_WHITE_PEONY.get())
                .add(ModBlocks.YELLOW_WHITE_PEONY.get())
                .add(ModBlocks.PURPLE_WHITE_PEONY.get())
                .add(ModBlocks.WU_HUA_LONG_YU_PEONY.get())
                .add(ModBlocks.MAUVE_PEONY.get());

        this.tag(ModTags.Blocks.CHINESE_ROSES)
                .add(ModBlocks.CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.PINK_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.YELLOW_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.RED_PINK_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.RED_YELLOW_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.RED_WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.PINK_WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.YELLOW_WHITE_CHINESE_ROSE_BUSH.get())
                .add(ModBlocks.CHINESE_ROSE.get())
                .add(ModBlocks.PINK_CHINESE_ROSE.get())
                .add(ModBlocks.YELLOW_CHINESE_ROSE.get())
                .add(ModBlocks.WHITE_CHINESE_ROSE.get())
                .add(ModBlocks.RED_PINK_CHINESE_ROSE.get())
                .add(ModBlocks.RED_YELLOW_CHINESE_ROSE.get())
                .add(ModBlocks.RED_WHITE_CHINESE_ROSE.get())
                .add(ModBlocks.PINK_WHITE_CHINESE_ROSE.get())
                .add(ModBlocks.YELLOW_WHITE_CHINESE_ROSE.get());

        this.tag(ModTags.Blocks.CHRYSANTHEMUMS)
                .add(ModBlocks.CHRYSANTHEMUM.get())
                .add(ModBlocks.GOLDEN_CHRYSANTHEMUM.get())
                .add(ModBlocks.GOLD_BACKED_SCARLET_MUM.get())
                .add(ModBlocks.WHITE_CHRYSANTHEMUM.get())
                .add(ModBlocks.GREEN_CHRYSANTHEMUM.get())
                .add(ModBlocks.PURPLE_CHRYSANTHEMUM.get())
                .add(ModBlocks.VIOLET_PINK_CHRYSANTHEMUM.get())
                .add(ModBlocks.PINK_CHRYSANTHEMUM.get())
                .add(ModBlocks.LIGHT_PINK_CHRYSANTHEMUM.get());

        this.tag(ModTags.Blocks.CAMELLIAS)
                .add(ModBlocks.CAMELLIA.get())
                .add(ModBlocks.PINK_CAMELLIA.get())
                .add(ModBlocks.WHITE_CAMELLIA.get())
                .add(ModBlocks.VERSICOLOR_CAMELLIA.get());

        this.tag(ModTags.Blocks.AZALEA)
                .add(Blocks.AZALEA)
                .add(Blocks.FLOWERING_AZALEA)
                .add(ModBlocks.CRIMSON_AZALEA.get());

        this.tag(ModTags.Blocks.CRABAPPLE)
                .add(ModBlocks.UPRIGHT_CRABAPPLE_SAPLING.get())
                .add(ModBlocks.WEEPING_CRABAPPLE_SAPLING.get());

        this.tag(ModTags.Blocks.OSMANTHUS)
                .add(ModBlocks.GOLDEN_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.ORANGE_OSMANTHUS_SAPLING.get())
                .add(ModBlocks.WHITE_OSMANTHUS_SAPLING.get());

        this.tag(ModTags.Blocks.APRICOT)
                .add(ModBlocks.PINK_APRICOT_SAPLING.get())
                .add(ModBlocks.WHITE_APRICOT_SAPLING.get());

        this.tag(ModTags.Blocks.PEACH)
                .add(ModBlocks.ORNAMENTAL_PEACH_SAPLING.get())
                .add(ModBlocks.WILD_PEACH_SAPLING.get());

        this.tag(ModTags.Blocks.PLUM)
                .add(ModBlocks.FLOWERING_PURPLE_LEAF_PLUM_SAPLING.get())
                .add(ModBlocks.PURPLE_LEAF_PLUM_SAPLING.get());

        this.tag(ModTags.Blocks.CHINESE_PARASOL)
                .add(ModBlocks.YELLOW_CHINESE_PARASOL_SAPLING.get())
                .add(ModBlocks.GREEN_CHINESE_PARASOL_SAPLING.get());
    }
}
