package com.jinlan.moreornplants.datagen;

import com.jinlan.moreornplants.MoreOrnPlants;
import com.jinlan.moreornplants.block.ModBlocks;
import com.jinlan.moreornplants.item.ModItems;
import com.jinlan.moreornplants.util.ForgeTags;
import com.jinlan.moreornplants.util.ModTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModItemTagGenerator extends ItemTagsProvider {
    public ModItemTagGenerator(PackOutput p_275343_, CompletableFuture<HolderLookup.Provider> p_275729_, CompletableFuture<TagLookup<Block>> p_275322_, @Nullable ExistingFileHelper existingFileHelper) {
        super(p_275343_, p_275729_, p_275322_, MoreOrnPlants.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider pProvider) {
        this.tag(ItemTags.FLOWERS)
                .addTag(ItemTags.SMALL_FLOWERS)
                .addTag(ItemTags.TALL_FLOWERS)
                .add(ModBlocks.RED_MEI_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_MEI_SAPLING.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_SAPLING.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_SAPLING.get().asItem())
                .add(ModBlocks.VERSICOLOR_MEI_SAPLING.get().asItem())
                .add(ModBlocks.RED_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.GREEN_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.PINK_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.VERSICOLOR_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.UPRIGHT_CRABAPPLE_SAPLING.get().asItem())
                .add(ModBlocks.WEEPING_CRABAPPLE_SAPLING.get().asItem())
                .add(ModBlocks.PINK_APRICOT_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_APRICOT_SAPLING.get().asItem())
                .add(ModBlocks.ORNAMENTAL_PEACH_SAPLING.get().asItem())
                .add(ModBlocks.WILD_PEACH_SAPLING.get().asItem())
                .add(ModBlocks.PEAR_SAPLING.get().asItem())
                .add(ModBlocks.FLOWERING_PURPLE_LEAF_PLUM_SAPLING.get().asItem())
                .add(ModBlocks.GOLDEN_OSMANTHUS_SAPLING.get().asItem())
                .add(ModBlocks.ORANGE_OSMANTHUS_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_OSMANTHUS_SAPLING.get().asItem())
                .add(ModBlocks.DOVE_TREE_SAPLING.get().asItem())
                .add(ModBlocks.CHINABERRY_SAPLING.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_SAPLING.get().asItem())
                .add(ModBlocks.CRAPE_MYRTLE_SAPLING.get().asItem())
                .add(ModBlocks.RED_MEI_LEAVES.get().asItem())
                .add(ModBlocks.WHITE_MEI_LEAVES.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_LEAVES.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_LEAVES.get().asItem())
                .add(ModBlocks.VERSICOLOR_MEI_LEAVES.get().asItem())
                .add(ModBlocks.PINK_WEEPING_MEI.get().asItem())
                .add(ModBlocks.RED_WEEPING_MEI.get().asItem())
                .add(ModBlocks.WHITE_WEEPING_MEI.get().asItem())
                .add(ModBlocks.GREEN_WEEPING_MEI.get().asItem())
                .add(ModBlocks.VERSICOLOR_WEEPING_MEI.get().asItem())
                .add(ModBlocks.UPRIGHT_CRABAPPLE_LEAVES.get().asItem())
                .add(ModBlocks.WEEPING_CRABAPPLE_LEAVES.get().asItem())
                .add(ModBlocks.WEEPING_CRABAPPLE.get().asItem())
                .add(ModBlocks.PINK_APRICOT_LEAVES.get().asItem())
                .add(ModBlocks.WHITE_APRICOT_LEAVES.get().asItem())
                .add(ModBlocks.ORNAMENTAL_PEACH_LEAVES.get().asItem())
                .add(ModBlocks.WILD_PEACH_LEAVES.get().asItem())
                .add(ModBlocks.PEAR_LEAVES.get().asItem())
                .add(ModBlocks.FLOWERING_PURPLE_LEAF_PLUM_LEAVES.get().asItem())
                .add(ModBlocks.GOLDEN_OSMANTHUS_LEAVES.get().asItem())
                .add(ModBlocks.ORANGE_OSMANTHUS_LEAVES.get().asItem())
                .add(ModBlocks.WHITE_OSMANTHUS_LEAVES.get().asItem())
                .add(ModBlocks.DOVE_TREE_BLOSSOM_LEAVES.get().asItem())
                .add(ModBlocks.CHINABERRY_LEAVES.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_LEAVES.get().asItem())
                .add(ModBlocks.CRAPE_MYRTLE_LEAVES.get().asItem())
                .add(ModBlocks.PEACH_PINK_PETALS.get().asItem());

        this.tag(ItemTags.LEAVES)
                .add(ModBlocks.RED_MEI_LEAVES.get().asItem())
                .add(ModBlocks.WHITE_MEI_LEAVES.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_LEAVES.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_LEAVES.get().asItem())
                .add(ModBlocks.VERSICOLOR_MEI_LEAVES.get().asItem())
                .add(ModBlocks.UPRIGHT_CRABAPPLE_LEAVES.get().asItem())
                .add(ModBlocks.WEEPING_CRABAPPLE_LEAVES.get().asItem())
                .add(ModBlocks.PINK_APRICOT_LEAVES.get().asItem())
                .add(ModBlocks.WHITE_APRICOT_LEAVES.get().asItem())
                .add(ModBlocks.ORNAMENTAL_PEACH_LEAVES.get().asItem())
                .add(ModBlocks.WILD_PEACH_LEAVES.get().asItem())
                .add(ModBlocks.PEAR_LEAVES.get().asItem())
                .add(ModBlocks.FLOWERING_PURPLE_LEAF_PLUM_LEAVES.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_LEAVES.get().asItem())
                .add(ModBlocks.GOLDEN_OSMANTHUS_LEAVES.get().asItem())
                .add(ModBlocks.ORANGE_OSMANTHUS_LEAVES.get().asItem())
                .add(ModBlocks.WHITE_OSMANTHUS_LEAVES.get().asItem())
                .add(ModBlocks.GOLDEN_GINKGO_LEAVES.get().asItem())
                .add(ModBlocks.GREEN_GINKGO_LEAVES.get().asItem())
                .add(ModBlocks.YELLOW_CHINESE_PARASOL_LEAVES.get().asItem())
                .add(ModBlocks.GREEN_CHINESE_PARASOL_LEAVES.get().asItem())
                .add(ModBlocks.SWEETGUM_LEAVES.get().asItem())
                .add(ModBlocks.CAMPHOR_LEAVES.get().asItem())
                .add(ModBlocks.NEW_CAMPHOR_LEAVES.get().asItem())
                .add(ModBlocks.DOVE_TREE_LEAVES.get().asItem())
                .add(ModBlocks.DOVE_TREE_BLOSSOM_LEAVES.get().asItem())
                .add(ModBlocks.CHINABERRY_LEAVES.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_LEAVES.get().asItem())
                .add(ModBlocks.CRAPE_MYRTLE_LEAVES.get().asItem());

        this.tag(ItemTags.LOGS_THAT_BURN)
                .addTag(ModTags.Items.RED_MEI_LOGS)
                .addTag(ModTags.Items.WHITE_MEI_LOGS)
                .addTag(ModTags.Items.GREEN_CALYX_MEI_LOGS)
                .addTag(ModTags.Items.DOUBLE_PINK_MEI_LOGS)
                .addTag(ModTags.Items.CRABAPPLE_LOGS)
                .addTag(ModTags.Items.APRICOT_LOGS)
                .addTag(ModTags.Items.PEACH_LOGS)
                .addTag(ModTags.Items.PEAR_LOGS)
                .addTag(ModTags.Items.PURPLE_LEAF_PLUM_LOGS)
                .addTag(ModTags.Items.OSMANTHUS_LOGS)
                .addTag(ModTags.Items.GINKGO_LOGS)
                .addTag(ModTags.Items.CHINESE_PARASOL_LOGS)
                .addTag(ModTags.Items.SWEETGUM_LOGS)
                .addTag(ModTags.Items.CAMPHOR_LOGS)
                .addTag(ModTags.Items.DOVE_TREE_LOGS)
                .addTag(ModTags.Items.CHINABERRY_LOGS)
                .addTag(ModTags.Items.DESERT_POPLAR_LOGS)
                .add(ModBlocks.CRAPE_MYRTLE_LOG.get().asItem())
                .add(ModBlocks.CRAPE_MYRTLE_WOOD.get().asItem());

        this.tag(ItemTags.PLANKS)
                .add(ModBlocks.RED_MEI_PLANKS.get().asItem())
                .add(ModBlocks.WHITE_MEI_PLANKS.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_PLANKS.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_PLANKS.get().asItem())
                .add(ModBlocks.CRABAPPLE_PLANKS.get().asItem())
                .add(ModBlocks.APRICOT_PLANKS.get().asItem())
                .add(ModBlocks.PEACH_PLANKS.get().asItem())
                .add(ModBlocks.PEAR_PLANKS.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_PLANKS.get().asItem())
                .add(ModBlocks.OSMANTHUS_PLANKS.get().asItem())
                .add(ModBlocks.GINKGO_PLANKS.get().asItem())
                .add(ModBlocks.CHINESE_PARASOL_PLANKS.get().asItem())
                .add(ModBlocks.SWEETGUM_PLANKS.get().asItem())
                .add(ModBlocks.CAMPHOR_PLANKS.get().asItem())
                .add(ModBlocks.DOVE_TREE_PLANKS.get().asItem())
                .add(ModBlocks.CHINABERRY_PLANKS.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_PLANKS.get().asItem());

        this.tag(ItemTags.WOODEN_STAIRS)
                .add(ModBlocks.RED_MEI_STAIRS.get().asItem())
                .add(ModBlocks.WHITE_MEI_STAIRS.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_STAIRS.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_STAIRS.get().asItem())
                .add(ModBlocks.CRABAPPLE_STAIRS.get().asItem())
                .add(ModBlocks.APRICOT_STAIRS.get().asItem())
                .add(ModBlocks.PEACH_STAIRS.get().asItem())
                .add(ModBlocks.PEAR_STAIRS.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_STAIRS.get().asItem())
                .add(ModBlocks.OSMANTHUS_STAIRS.get().asItem())
                .add(ModBlocks.GINKGO_STAIRS.get().asItem())
                .add(ModBlocks.CHINESE_PARASOL_STAIRS.get().asItem())
                .add(ModBlocks.SWEETGUM_STAIRS.get().asItem())
                .add(ModBlocks.CAMPHOR_STAIRS.get().asItem())
                .add(ModBlocks.DOVE_TREE_STAIRS.get().asItem())
                .add(ModBlocks.CHINABERRY_STAIRS.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_STAIRS.get().asItem());

        this.tag(ItemTags.WOODEN_SLABS)
                .add(ModBlocks.RED_MEI_SLAB.get().asItem())
                .add(ModBlocks.WHITE_MEI_SLAB.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_SLAB.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_SLAB.get().asItem())
                .add(ModBlocks.CRABAPPLE_SLAB.get().asItem())
                .add(ModBlocks.APRICOT_SLAB.get().asItem())
                .add(ModBlocks.PEACH_SLAB.get().asItem())
                .add(ModBlocks.PEAR_SLAB.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_SLAB.get().asItem())
                .add(ModBlocks.OSMANTHUS_SLAB.get().asItem())
                .add(ModBlocks.GINKGO_SLAB.get().asItem())
                .add(ModBlocks.CHINESE_PARASOL_SLAB.get().asItem())
                .add(ModBlocks.SWEETGUM_SLAB.get().asItem())
                .add(ModBlocks.CAMPHOR_SLAB.get().asItem())
                .add(ModBlocks.DOVE_TREE_SLAB.get().asItem())
                .add(ModBlocks.CHINABERRY_SLAB.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_SLAB.get().asItem());

        this.tag(ItemTags.WOODEN_BUTTONS)
                .add(ModBlocks.RED_MEI_BUTTON.get().asItem())
                .add(ModBlocks.WHITE_MEI_BUTTON.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_BUTTON.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_BUTTON.get().asItem())
                .add(ModBlocks.CRABAPPLE_BUTTON.get().asItem())
                .add(ModBlocks.APRICOT_BUTTON.get().asItem())
                .add(ModBlocks.PEACH_BUTTON.get().asItem())
                .add(ModBlocks.PEAR_BUTTON.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_BUTTON.get().asItem())
                .add(ModBlocks.OSMANTHUS_BUTTON.get().asItem())
                .add(ModBlocks.GINKGO_BUTTON.get().asItem())
                .add(ModBlocks.CHINESE_PARASOL_BUTTON.get().asItem())
                .add(ModBlocks.SWEETGUM_BUTTON.get().asItem())
                .add(ModBlocks.CAMPHOR_BUTTON.get().asItem())
                .add(ModBlocks.DOVE_TREE_BUTTON.get().asItem())
                .add(ModBlocks.CHINABERRY_BUTTON.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_BUTTON.get().asItem());

        this.tag(ItemTags.WOODEN_PRESSURE_PLATES)
                .add(ModBlocks.RED_MEI_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.WHITE_MEI_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.CRABAPPLE_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.APRICOT_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.PEACH_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.PEAR_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.OSMANTHUS_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.GINKGO_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.CHINESE_PARASOL_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.SWEETGUM_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.CAMPHOR_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.DOVE_TREE_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.CHINABERRY_PRESSURE_PLATE.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_PRESSURE_PLATE.get().asItem());

        this.tag(ItemTags.WOODEN_FENCES)
                .add(ModBlocks.RED_MEI_FENCE.get().asItem())
                .add(ModBlocks.WHITE_MEI_FENCE.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_FENCE.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_FENCE.get().asItem())
                .add(ModBlocks.CRABAPPLE_FENCE.get().asItem())
                .add(ModBlocks.APRICOT_FENCE.get().asItem())
                .add(ModBlocks.PEACH_FENCE.get().asItem())
                .add(ModBlocks.PEAR_FENCE.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_FENCE.get().asItem())
                .add(ModBlocks.OSMANTHUS_FENCE.get().asItem())
                .add(ModBlocks.GINKGO_FENCE.get().asItem())
                .add(ModBlocks.CHINESE_PARASOL_FENCE.get().asItem())
                .add(ModBlocks.SWEETGUM_FENCE.get().asItem())
                .add(ModBlocks.CAMPHOR_FENCE.get().asItem())
                .add(ModBlocks.DOVE_TREE_FENCE.get().asItem())
                .add(ModBlocks.CHINABERRY_FENCE.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_FENCE.get().asItem());

        this.tag(ItemTags.FENCE_GATES)
                .add(ModBlocks.RED_MEI_FENCE_GATE.get().asItem())
                .add(ModBlocks.WHITE_MEI_FENCE_GATE.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_FENCE_GATE.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_FENCE_GATE.get().asItem())
                .add(ModBlocks.CRABAPPLE_FENCE_GATE.get().asItem())
                .add(ModBlocks.APRICOT_FENCE_GATE.get().asItem())
                .add(ModBlocks.PEACH_FENCE_GATE.get().asItem())
                .add(ModBlocks.PEAR_FENCE_GATE.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_FENCE_GATE.get().asItem())
                .add(ModBlocks.OSMANTHUS_FENCE_GATE.get().asItem())
                .add(ModBlocks.GINKGO_FENCE_GATE.get().asItem())
                .add(ModBlocks.CHINESE_PARASOL_FENCE_GATE.get().asItem())
                .add(ModBlocks.SWEETGUM_FENCE_GATE.get().asItem())
                .add(ModBlocks.CAMPHOR_FENCE_GATE.get().asItem())
                .add(ModBlocks.DOVE_TREE_FENCE_GATE.get().asItem())
                .add(ModBlocks.CHINABERRY_FENCE_GATE.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_FENCE_GATE.get().asItem());

        this.tag(ItemTags.WOODEN_DOORS)
                .add(ModBlocks.RED_MEI_DOOR.get().asItem())
                .add(ModBlocks.WHITE_MEI_DOOR.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_DOOR.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_DOOR.get().asItem())
                .add(ModBlocks.CRABAPPLE_DOOR.get().asItem())
                .add(ModBlocks.APRICOT_DOOR.get().asItem())
                .add(ModBlocks.PEACH_DOOR.get().asItem())
                .add(ModBlocks.PEAR_DOOR.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_DOOR.get().asItem())
                .add(ModBlocks.OSMANTHUS_DOOR.get().asItem())
                .add(ModBlocks.GINKGO_DOOR.get().asItem())
                .add(ModBlocks.CHINESE_PARASOL_DOOR.get().asItem())
                .add(ModBlocks.SWEETGUM_DOOR.get().asItem())
                .add(ModBlocks.CAMPHOR_DOOR.get().asItem())
                .add(ModBlocks.DOVE_TREE_DOOR.get().asItem())
                .add(ModBlocks.CHINABERRY_DOOR.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_DOOR.get().asItem());

        this.tag(ItemTags.WOODEN_TRAPDOORS)
                .add(ModBlocks.RED_MEI_TRAPDOOR.get().asItem())
                .add(ModBlocks.WHITE_MEI_TRAPDOOR.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_TRAPDOOR.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_TRAPDOOR.get().asItem())
                .add(ModBlocks.CRABAPPLE_TRAPDOOR.get().asItem())
                .add(ModBlocks.APRICOT_TRAPDOOR.get().asItem())
                .add(ModBlocks.PEACH_TRAPDOOR.get().asItem())
                .add(ModBlocks.PEAR_TRAPDOOR.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_TRAPDOOR.get().asItem())
                .add(ModBlocks.OSMANTHUS_TRAPDOOR.get().asItem())
                .add(ModBlocks.GINKGO_TRAPDOOR.get().asItem())
                .add(ModBlocks.CHINESE_PARASOL_TRAPDOOR.get().asItem())
                .add(ModBlocks.SWEETGUM_TRAPDOOR.get().asItem())
                .add(ModBlocks.CAMPHOR_TRAPDOOR.get().asItem())
                .add(ModBlocks.DOVE_TREE_TRAPDOOR.get().asItem())
                .add(ModBlocks.CHINABERRY_TRAPDOOR.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_TRAPDOOR.get().asItem());

        this.tag(ItemTags.SIGNS)
                .add(ModItems.RED_MEI_SIGN.get())
                .add(ModItems.WHITE_MEI_SIGN.get())
                .add(ModItems.GREEN_CALYX_MEI_SIGN.get())
                .add(ModItems.DOUBLE_PINK_MEI_SIGN.get())
                .add(ModItems.CRABAPPLE_SIGN.get())
                .add(ModItems.APRICOT_SIGN.get())
                .add(ModItems.PEACH_SIGN.get())
                .add(ModItems.PEAR_SIGN.get())
                .add(ModItems.PURPLE_LEAF_PLUM_SIGN.get())
                .add(ModItems.OSMANTHUS_SIGN.get())
                .add(ModItems.GINKGO_SIGN.get())
                .add(ModItems.CHINESE_PARASOL_SIGN.get())
                .add(ModItems.SWEETGUM_SIGN.get())
                .add(ModItems.CAMPHOR_SIGN.get())
                .add(ModItems.DOVE_TREE_SIGN.get())
                .add(ModItems.CHINABERRY_SIGN.get())
                .add(ModItems.DESERT_POPLAR_SIGN.get());

        this.tag(ItemTags.HANGING_SIGNS)
                .add(ModItems.RED_MEI_HANGING_SIGN.get())
                .add(ModItems.WHITE_MEI_HANGING_SIGN.get())
                .add(ModItems.GREEN_CALYX_MEI_HANGING_SIGN.get())
                .add(ModItems.DOUBLE_PINK_MEI_HANGING_SIGN.get())
                .add(ModItems.CRABAPPLE_HANGING_SIGN.get())
                .add(ModItems.APRICOT_HANGING_SIGN.get())
                .add(ModItems.PEACH_HANGING_SIGN.get())
                .add(ModItems.PEAR_HANGING_SIGN.get())
                .add(ModItems.PURPLE_LEAF_PLUM_HANGING_SIGN.get())
                .add(ModItems.OSMANTHUS_HANGING_SIGN.get())
                .add(ModItems.GINKGO_HANGING_SIGN.get())
                .add(ModItems.CHINESE_PARASOL_HANGING_SIGN.get())
                .add(ModItems.SWEETGUM_HANGING_SIGN.get())
                .add(ModItems.CAMPHOR_HANGING_SIGN.get())
                .add(ModItems.DOVE_TREE_HANGING_SIGN.get())
                .add(ModItems.CHINABERRY_HANGING_SIGN.get())
                .add(ModItems.DESERT_POPLAR_HANGING_SIGN.get());

        this.tag(ItemTags.BOATS)
                .add(ModItems.RED_MEI_BOAT.get())
                .add(ModItems.WHITE_MEI_BOAT.get())
                .add(ModItems.GREEN_CALYX_MEI_BOAT.get())
                .add(ModItems.DOUBLE_PINK_MEI_BOAT.get())
                .add(ModItems.CRABAPPLE_BOAT.get())
                .add(ModItems.APRICOT_BOAT.get())
                .add(ModItems.PEACH_BOAT.get())
                .add(ModItems.PEAR_BOAT.get())
                .add(ModItems.PURPLE_LEAF_PLUM_BOAT.get())
                .add(ModItems.OSMANTHUS_BOAT.get())
                .add(ModItems.GINKGO_BOAT.get())
                .add(ModItems.SWEETGUM_BOAT.get())
                .add(ModItems.CHINESE_PARASOL_BOAT.get())
                .add(ModItems.CAMPHOR_BOAT.get())
                .add(ModItems.DOVE_TREE_BOAT.get())
                .add(ModItems.CHINABERRY_BOAT.get())
                .add(ModItems.DESERT_POPLAR_BOAT.get());

        this.tag(ItemTags.CHEST_BOATS)
                .add(ModItems.RED_MEI_CHEST_BOAT.get())
                .add(ModItems.WHITE_MEI_CHEST_BOAT.get())
                .add(ModItems.GREEN_CALYX_MEI_CHEST_BOAT.get())
                .add(ModItems.DOUBLE_PINK_MEI_CHEST_BOAT.get())
                .add(ModItems.CRABAPPLE_CHEST_BOAT.get())
                .add(ModItems.APRICOT_CHEST_BOAT.get())
                .add(ModItems.PEACH_CHEST_BOAT.get())
                .add(ModItems.PEAR_CHEST_BOAT.get())
                .add(ModItems.PURPLE_LEAF_PLUM_CHEST_BOAT.get())
                .add(ModItems.OSMANTHUS_CHEST_BOAT.get())
                .add(ModItems.GINKGO_CHEST_BOAT.get())
                .add(ModItems.SWEETGUM_CHEST_BOAT.get())
                .add(ModItems.CHINESE_PARASOL_CHEST_BOAT.get())
                .add(ModItems.CAMPHOR_CHEST_BOAT.get())
                .add(ModItems.DOVE_TREE_CHEST_BOAT.get())
                .add(ModItems.CHINABERRY_CHEST_BOAT.get())
                .add(ModItems.DESERT_POPLAR_CHEST_BOAT.get());

        this.tag(ModTags.Items.RED_MEI_LOGS)
                .add(ModBlocks.RED_MEI_LOG.get().asItem(),
                        ModBlocks.RED_MEI_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_RED_MEI_LOG.get().asItem(),
                        ModBlocks.STRIPPED_RED_MEI_WOOD.get().asItem());
        this.tag(ModTags.Items.WHITE_MEI_LOGS)
                .add(ModBlocks.WHITE_MEI_LOG.get().asItem(),
                        ModBlocks.WHITE_MEI_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_WHITE_MEI_LOG.get().asItem(),
                        ModBlocks.STRIPPED_WHITE_MEI_WOOD.get().asItem());
        this.tag(ModTags.Items.GREEN_CALYX_MEI_LOGS)
                .add(ModBlocks.GREEN_CALYX_MEI_LOG.get().asItem(),
                        ModBlocks.GREEN_CALYX_MEI_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_GREEN_CALYX_MEI_LOG.get().asItem(),
                        ModBlocks.STRIPPED_GREEN_CALYX_MEI_WOOD.get().asItem());
        this.tag(ModTags.Items.DOUBLE_PINK_MEI_LOGS)
                .add(ModBlocks.DOUBLE_PINK_MEI_LOG.get().asItem(),
                        ModBlocks.DOUBLE_PINK_MEI_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_DOUBLE_PINK_MEI_LOG.get().asItem(),
                        ModBlocks.STRIPPED_DOUBLE_PINK_MEI_WOOD.get().asItem());
        this.tag(ModTags.Items.CRABAPPLE_LOGS)
                .add(ModBlocks.CRABAPPLE_LOG.get().asItem(),
                        ModBlocks.CRABAPPLE_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_CRABAPPLE_LOG.get().asItem(),
                        ModBlocks.STRIPPED_CRABAPPLE_WOOD.get().asItem());
        this.tag(ModTags.Items.APRICOT_LOGS)
                .add(ModBlocks.APRICOT_LOG.get().asItem(),
                        ModBlocks.APRICOT_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_APRICOT_LOG.get().asItem(),
                        ModBlocks.STRIPPED_APRICOT_WOOD.get().asItem());
        this.tag(ModTags.Items.PEACH_LOGS)
                .add(ModBlocks.PEACH_LOG.get().asItem(),
                        ModBlocks.PEACH_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_PEACH_LOG.get().asItem(),
                        ModBlocks.STRIPPED_PEACH_WOOD.get().asItem());
        this.tag(ModTags.Items.PEAR_LOGS)
                .add(ModBlocks.PEAR_LOG.get().asItem(),
                        ModBlocks.PEAR_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_PEAR_LOG.get().asItem(),
                        ModBlocks.STRIPPED_PEAR_WOOD.get().asItem());
        this.tag(ModTags.Items.PURPLE_LEAF_PLUM_LOGS)
                .add(ModBlocks.PURPLE_LEAF_PLUM_LOG.get().asItem(),
                        ModBlocks.PURPLE_LEAF_PLUM_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_PURPLE_LEAF_PLUM_LOG.get().asItem(),
                        ModBlocks.STRIPPED_PURPLE_LEAF_PLUM_WOOD.get().asItem());
        this.tag(ModTags.Items.OSMANTHUS_LOGS)
                .add(ModBlocks.OSMANTHUS_LOG.get().asItem(),
                        ModBlocks.OSMANTHUS_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_OSMANTHUS_LOG.get().asItem(),
                        ModBlocks.STRIPPED_OSMANTHUS_WOOD.get().asItem());
        this.tag(ModTags.Items.GINKGO_LOGS)
                .add(ModBlocks.GINKGO_LOG.get().asItem(),
                        ModBlocks.GINKGO_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_GINKGO_LOG.get().asItem(),
                        ModBlocks.STRIPPED_GINKGO_WOOD.get().asItem());
        this.tag(ModTags.Items.CHINESE_PARASOL_LOGS)
                .add(ModBlocks.CHINESE_PARASOL_LOG.get().asItem(),
                        ModBlocks.CHINESE_PARASOL_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_CHINESE_PARASOL_LOG.get().asItem(),
                        ModBlocks.STRIPPED_CHINESE_PARASOL_WOOD.get().asItem());
        this.tag(ModTags.Items.SWEETGUM_LOGS)
                .add(ModBlocks.SWEETGUM_LOG.get().asItem(),
                        ModBlocks.SWEETGUM_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_SWEETGUM_LOG.get().asItem(),
                        ModBlocks.STRIPPED_SWEETGUM_WOOD.get().asItem());
        this.tag(ModTags.Items.CAMPHOR_LOGS)
                .add(ModBlocks.CAMPHOR_LOG.get().asItem(),
                        ModBlocks.CAMPHOR_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_CAMPHOR_LOG.get().asItem(),
                        ModBlocks.STRIPPED_CAMPHOR_WOOD.get().asItem());
        this.tag(ModTags.Items.DOVE_TREE_LOGS)
                .add(ModBlocks.DOVE_TREE_LOG.get().asItem(),
                        ModBlocks.DOVE_TREE_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_DOVE_TREE_LOG.get().asItem(),
                        ModBlocks.STRIPPED_DOVE_TREE_WOOD.get().asItem());
        this.tag(ModTags.Items.CHINABERRY_LOGS)
                .add(ModBlocks.CHINABERRY_LOG.get().asItem(),
                        ModBlocks.CHINABERRY_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_CHINABERRY_LOG.get().asItem(),
                        ModBlocks.STRIPPED_CHINABERRY_WOOD.get().asItem());
        this.tag(ModTags.Items.DESERT_POPLAR_LOGS)
                .add(ModBlocks.DESERT_POPLAR_LOG.get().asItem(),
                        ModBlocks.DESERT_POPLAR_WOOD.get().asItem(),
                        ModBlocks.STRIPPED_DESERT_POPLAR_LOG.get().asItem(),
                        ModBlocks.STRIPPED_DESERT_POPLAR_WOOD.get().asItem());

        this.tag(ItemTags.SAPLINGS)
                .add(ModBlocks.RED_MEI_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_MEI_SAPLING.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_SAPLING.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_SAPLING.get().asItem())
                .add(ModBlocks.VERSICOLOR_MEI_SAPLING.get().asItem())
                .add(ModBlocks.RED_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.GREEN_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.PINK_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.VERSICOLOR_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.UPRIGHT_CRABAPPLE_SAPLING.get().asItem())
                .add(ModBlocks.WEEPING_CRABAPPLE_SAPLING.get().asItem())
                .add(ModBlocks.PINK_APRICOT_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_APRICOT_SAPLING.get().asItem())
                .add(ModBlocks.ORNAMENTAL_PEACH_SAPLING.get().asItem())
                .add(ModBlocks.WILD_PEACH_SAPLING.get().asItem())
                .add(ModBlocks.PEAR_SAPLING.get().asItem())
                .add(ModBlocks.FLOWERING_PURPLE_LEAF_PLUM_SAPLING.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_SAPLING.get().asItem())
                .add(ModBlocks.GOLDEN_OSMANTHUS_SAPLING.get().asItem())
                .add(ModBlocks.ORANGE_OSMANTHUS_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_OSMANTHUS_SAPLING.get().asItem())
                .add(ModBlocks.GOLDEN_GINKGO_SAPLING.get().asItem())
                .add(ModBlocks.GREEN_GINKGO_SAPLING.get().asItem())
                .add(ModBlocks.YELLOW_CHINESE_PARASOL_SAPLING.get().asItem())
                .add(ModBlocks.GREEN_CHINESE_PARASOL_SAPLING.get().asItem())
                .add(ModBlocks.SWEETGUM_SAPLING.get().asItem())
                .add(ModBlocks.CAMPHOR_SAPLING.get().asItem())
                .add(ModBlocks.DOVE_TREE_SAPLING.get().asItem())
                .add(ModBlocks.CHINABERRY_SAPLING.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_SAPLING.get().asItem())
                .add(ModBlocks.CRAPE_MYRTLE_SAPLING.get().asItem());

        this.tag(ItemTags.SMALL_FLOWERS)
                .add(ModBlocks.WINTER_JASMINE.get().asItem())
                .addTag(ForgeTags.Items.CHRYSANTHEMUM)
                .add(ModBlocks.SPRING_CYMBIDIUM.get().asItem())
                .addTag(ForgeTags.Items.HERBACEOUS_PEONY)
                .add(ModBlocks.CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.PINK_CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.YELLOW_CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.WHITE_CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.RED_PINK_CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.RED_YELLOW_CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.RED_WHITE_CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.PINK_WHITE_CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.YELLOW_WHITE_CHINESE_ROSE_BUSH.get().asItem())
                .addTag(ForgeTags.Items.CAMELLIA)
                .add(ModBlocks.CRIMSON_AZALEA.get().asItem());

        this.tag(ItemTags.TALL_FLOWERS)
                .add(ModBlocks.WINTERSWEET.get().asItem())
                .add(ModBlocks.TWO_QIAO_PEONY.get().asItem())
                .add(ModBlocks.VERSICOLOR_PEONY.get().asItem())
                .add(ModBlocks.CHINESE_ROSE.get().asItem())
                .add(ModBlocks.PINK_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.YELLOW_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.WHITE_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.RED_PINK_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.RED_YELLOW_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.RED_WHITE_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.PINK_WHITE_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.YELLOW_WHITE_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.CRAPE_MYRTLE.get().asItem())
                .add(ModBlocks.COTTON_ROSE.get().asItem())
                .addTag(ForgeTags.Items.LOTUS);

        this.tag(ForgeTags.Items.PLANT_IN_FLORILEGIUM)
                .addTag(ForgeTags.Items.MEI_SAPLING)
                .addTag(ForgeTags.Items.CRABAPPLE_SAPLING)
                .addTag(ForgeTags.Items.APRICOT_SAPLING)
                .addTag(ForgeTags.Items.PEACH_SAPLING)
                .add(ModBlocks.PEAR_SAPLING.get().asItem())
                .addTag(ForgeTags.Items.PLUM_SAPLING)
                .addTag(ForgeTags.Items.OSMANTHUS_SAPLING)
                .addTag(ForgeTags.Items.GINKGO_SAPLING)
                .addTag(ForgeTags.Items.CHINESE_PARASOL_SAPLING)
                .add(ModBlocks.SWEETGUM_SAPLING.get().asItem())
                .add(ModBlocks.CAMPHOR_SAPLING.get().asItem())
                .add(ModBlocks.DOVE_TREE_SAPLING.get().asItem())
                .add(ModBlocks.CHINABERRY_SAPLING.get().asItem())
                .add(ModBlocks.DESERT_POPLAR_SAPLING.get().asItem())
                .addTag(ForgeTags.Items.CHRYSANTHEMUM)
                .add(ModBlocks.SPRING_CYMBIDIUM.get().asItem())
                .addTag(ForgeTags.Items.LOTUS)
                .addTag(ForgeTags.Items.HERBACEOUS_PEONY)
                .addTag(ForgeTags.Items.CHINESE_ROSE)
                .addTag(ForgeTags.Items.CAMELLIA)
                .addTag(ForgeTags.Items.AZALEA)
                .addTag(ForgeTags.Items.WINTERSWEET)
                .addTag(ForgeTags.Items.TREE_PEONY)
                .addTag(ForgeTags.Items.CRAPE_MYRTLE)
                .add(ModBlocks.COTTON_ROSE.get().asItem())
                .add(Blocks.FLOWERING_AZALEA.asItem())
                .add(Blocks.POPPY.asItem())
                .add(Blocks.ROSE_BUSH.asItem())
                .add(Blocks.SUNFLOWER.asItem())
                .add(Blocks.LILAC.asItem());

        this.tag(ForgeTags.Items.WINTERSWEET)
                .add(ModBlocks.WINTERSWEET.get().asItem());

        this.tag(ForgeTags.Items.MEI_SAPLING)
                .add(ModBlocks.RED_MEI_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_MEI_SAPLING.get().asItem())
                .add(ModBlocks.GREEN_CALYX_MEI_SAPLING.get().asItem())
                .add(ModBlocks.DOUBLE_PINK_MEI_SAPLING.get().asItem())
                .add(ModBlocks.VERSICOLOR_MEI_SAPLING.get().asItem())
                .add(ModBlocks.RED_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.GREEN_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.PINK_WEEPING_MEI_SAPLING.get().asItem())
                .add(ModBlocks.VERSICOLOR_WEEPING_MEI_SAPLING.get().asItem());

        this.tag(ForgeTags.Items.TREE_PEONY)
                .add(Blocks.PEONY.asItem())
                .add(ModBlocks.TWO_QIAO_PEONY.get().asItem())
                .add(ModBlocks.VERSICOLOR_PEONY.get().asItem());

        this.tag(ForgeTags.Items.HERBACEOUS_PEONY)
                .add(ModBlocks.PEONY.get().asItem())
                .add(ModBlocks.LIGHT_PINK_PEONY.get().asItem())
                .add(ModBlocks.VIOLET_PINK_PEONY.get().asItem())
                .add(ModBlocks.PINK_PEONY.get().asItem())
                .add(ModBlocks.RED_PEONY.get().asItem())
                .add(ModBlocks.LIGHT_RED_PEONY.get().asItem())
                .add(ModBlocks.INK_RED_PEONY.get().asItem())
                .add(ModBlocks.VERMILION_PEONY.get().asItem())
                .add(ModBlocks.PURPLE_PEONY.get().asItem())
                .add(ModBlocks.LIGHT_PURPLE_PEONY.get().asItem())
                .add(ModBlocks.INK_PURPLE_PEONY.get().asItem())
                .add(ModBlocks.VIOLET_PEONY.get().asItem())
                .add(ModBlocks.YELLOW_PEONY.get().asItem())
                .add(ModBlocks.LIGHT_YELLOW_PEONY.get().asItem())
                .add(ModBlocks.OCHRE_YELLOW_PEONY.get().asItem())
                .add(ModBlocks.GOLDEN_PEONY.get().asItem())
                .add(ModBlocks.WHITE_PEONY.get().asItem())
                .add(ModBlocks.INK_PEONY.get().asItem())
                .add(ModBlocks.BLUE_PEONY.get().asItem())
                .add(ModBlocks.GREEN_PEONY.get().asItem())
                .add(ModBlocks.COLORFUL_PEONY.get().asItem())
                .add(ModBlocks.LIGHT_COLORFUL_PEONY.get().asItem())
                .add(ModBlocks.INK_COLORFUL_PEONY.get().asItem())
                .add(ModBlocks.RED_WHITE_PEONY.get().asItem())
                .add(ModBlocks.PINK_WHITE_PEONY.get().asItem())
                .add(ModBlocks.YELLOW_WHITE_PEONY.get().asItem())
                .add(ModBlocks.PURPLE_WHITE_PEONY.get().asItem())
                .add(ModBlocks.WU_HUA_LONG_YU_PEONY.get().asItem())
                .add(ModBlocks.MAUVE_PEONY.get().asItem());

        this.tag(ForgeTags.Items.CHINESE_ROSE)
                .add(ModBlocks.CHINESE_ROSE.get().asItem())
                .add(ModBlocks.PINK_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.YELLOW_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.WHITE_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.RED_PINK_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.RED_YELLOW_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.RED_WHITE_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.PINK_WHITE_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.YELLOW_WHITE_CHINESE_ROSE.get().asItem());

        this.tag(ForgeTags.Items.CHRYSANTHEMUM)
                .add(ModBlocks.CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.GOLDEN_CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.GOLD_BACKED_SCARLET_MUM.get().asItem())
                .add(ModBlocks.WHITE_CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.GREEN_CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.PURPLE_CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.VIOLET_PINK_CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.PINK_CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.LIGHT_PINK_CHRYSANTHEMUM.get().asItem());

        this.tag(ForgeTags.Items.CAMELLIA)
                .add(ModBlocks.CAMELLIA.get().asItem())
                .add(ModBlocks.PINK_CAMELLIA.get().asItem())
                .add(ModBlocks.WHITE_CAMELLIA.get().asItem())
                .add(ModBlocks.VERSICOLOR_CAMELLIA.get().asItem());

        this.tag(ForgeTags.Items.AZALEA)
                .add(Blocks.AZALEA.asItem())
                .add(Blocks.FLOWERING_AZALEA.asItem())
                .add(ModBlocks.CRIMSON_AZALEA.get().asItem());

        this.tag(ForgeTags.Items.CRABAPPLE_SAPLING)
                .add(ModBlocks.UPRIGHT_CRABAPPLE_SAPLING.get().asItem())
                .add(ModBlocks.WEEPING_CRABAPPLE_SAPLING.get().asItem());

        this.tag(ForgeTags.Items.OSMANTHUS_SAPLING)
                .add(ModBlocks.GOLDEN_OSMANTHUS_SAPLING.get().asItem())
                .add(ModBlocks.ORANGE_OSMANTHUS_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_OSMANTHUS_SAPLING.get().asItem());

        this.tag(ForgeTags.Items.APRICOT_SAPLING)
                .add(ModBlocks.PINK_APRICOT_SAPLING.get().asItem())
                .add(ModBlocks.WHITE_APRICOT_SAPLING.get().asItem());

        this.tag(ForgeTags.Items.PEACH_SAPLING)
                .add(ModBlocks.ORNAMENTAL_PEACH_SAPLING.get().asItem())
                .add(ModBlocks.WILD_PEACH_SAPLING.get().asItem());

        this.tag(ForgeTags.Items.PLUM_SAPLING)
                .add(ModBlocks.FLOWERING_PURPLE_LEAF_PLUM_SAPLING.get().asItem())
                .add(ModBlocks.PURPLE_LEAF_PLUM_SAPLING.get().asItem());

        this.tag(ForgeTags.Items.GINKGO_SAPLING)
                .add(ModBlocks.GOLDEN_GINKGO_SAPLING.get().asItem())
                .add(ModBlocks.GREEN_GINKGO_SAPLING.get().asItem());

        this.tag(ForgeTags.Items.CHINESE_PARASOL_SAPLING)
                .add(ModBlocks.YELLOW_CHINESE_PARASOL_SAPLING.get().asItem())
                .add(ModBlocks.GREEN_CHINESE_PARASOL_SAPLING.get().asItem());

        this.tag(ForgeTags.Items.CRAPE_MYRTLE)
                .add(ModBlocks.CRAPE_MYRTLE.get().asItem())
                .add(ModBlocks.CRAPE_MYRTLE_SAPLING.get().asItem());

        this.tag(ForgeTags.Items.BAMBOO)
                .add(Blocks.BAMBOO.asItem())
                .add(ModBlocks.MOTTLED_BAMBOO.get().asItem())
                .add(ModBlocks.BLACK_BAMBOO.get().asItem());

        this.tag(ForgeTags.Items.LOTUS)
                .add(ModBlocks.LOTUS.get().asItem())
                .add(ModBlocks.WHITE_LOTUS.get().asItem());

        this.tag(ModTags.Items.RED_DYE)
                .add(ModBlocks.RED_PEONY.get().asItem())
                .add(ModBlocks.LIGHT_RED_PEONY.get().asItem())
                .add(ModBlocks.INK_RED_PEONY.get().asItem())
                .add(ModBlocks.VERMILION_PEONY.get().asItem())
                .add(ModBlocks.CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.CHINESE_ROSE.get().asItem())
                .add(ModBlocks.CAMELLIA.get().asItem())
                .add(ModBlocks.CRIMSON_AZALEA.get().asItem())
                .add(ModItems.SWEETGUM_LEAF_0.get())
                .add(ModItems.SWEETGUM_LEAF_1.get());

        this.tag(ModTags.Items.PINK_DYE)
                .add(ModBlocks.PINK_CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.PEONY.get().asItem())
                .add(ModBlocks.LIGHT_PINK_PEONY.get().asItem())
                .add(ModBlocks.VIOLET_PINK_PEONY.get().asItem())
                .add(ModBlocks.PINK_PEONY.get().asItem())
                .add(ModBlocks.MAUVE_PEONY.get().asItem())
                .add(ModBlocks.PINK_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.PINK_CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.PINK_CAMELLIA.get().asItem())
                .add(ModBlocks.PEACH_PINK_PETALS.get().asItem())
                .add(ModBlocks.WEEPING_CRABAPPLE.get().asItem())
                .add(ModBlocks.COTTON_ROSE.get().asItem())
                .add(ModBlocks.LOTUS.get().asItem())
                .add(ModItems.ORNAMENTAL_PEACH_PETALS.get())
                .add(ModItems.WILD_PEACH_PETALS.get());

        this.tag(ModTags.Items.WHITE_DYE)
                .add(ModBlocks.WHITE_CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.WHITE_PEONY.get().asItem())
                .add(ModBlocks.WHITE_CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.WHITE_CAMELLIA.get().asItem())
                .add(ModBlocks.WHITE_LOTUS.get().asItem());

        this.tag(ModTags.Items.YELLOW_DYE)
                .add(ModBlocks.WINTERSWEET.get().asItem())
                .add(ModBlocks.CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.YELLOW_PEONY.get().asItem())
                .add(ModBlocks.LIGHT_YELLOW_PEONY.get().asItem())
                .add(ModBlocks.OCHRE_YELLOW_PEONY.get().asItem())
                .add(ModBlocks.GOLDEN_PEONY.get().asItem())
                .add(ModBlocks.YELLOW_CHINESE_ROSE.get().asItem())
                .add(ModBlocks.YELLOW_CHINESE_ROSE_BUSH.get().asItem())
                .add(ModBlocks.WINTER_JASMINE.get().asItem())
                .add(ModItems.CHINESE_PARASOL_LEAF_0.get())
                .add(ModItems.GINKGO_LEAF.get());

        this.tag(ModTags.Items.ORANGE_DYE)
                .add(ModItems.CHINESE_PARASOL_LEAF_1.get());

        this.tag(ModTags.Items.PURPLE_DYE)
                .add(ModBlocks.PURPLE_CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.PURPLE_PEONY.get().asItem())
                .add(ModBlocks.LIGHT_PURPLE_PEONY.get().asItem())
                .add(ModBlocks.INK_PURPLE_PEONY.get().asItem())
                .add(ModBlocks.VIOLET_PEONY.get().asItem())
                .addTag(ForgeTags.Items.CRAPE_MYRTLE);

        this.tag(ModTags.Items.LIME_DYE)
                .add(ModBlocks.GREEN_CHRYSANTHEMUM.get().asItem())
                .add(ModBlocks.GREEN_PEONY.get().asItem());

        this.tag(ModTags.Items.GREEN_DYE)
                .add(ModBlocks.SPRING_CYMBIDIUM.get().asItem())
                .add(ModBlocks.LOTUS_LEAF.get().asItem());

        this.tag(ModTags.Items.LIGHT_BLUE_DYE)
                .add(ModBlocks.BLUE_PEONY.get().asItem());

        this.tag(ModTags.Items.BLACK_DYE)
                .add(ModBlocks.INK_PEONY.get().asItem());

        this.tag(ForgeTags.Items.VEGETABLES)
                .addTag(ForgeTags.Items.VEGETABLES_BAMBOO_SHOOTS)
                .addTag(ForgeTags.Items.VEGETABLES_BAMBOO_SPROUTS)
                .addTag(ForgeTags.Items.VEGETABLES_LOTUS_ROOT)
                .addTag(ForgeTags.Items.VEGETABLES_LOTUS_SEED)
                .addTag(ForgeTags.Items.VEGETABLES_LOTUS_NUT);

        this.tag(ForgeTags.Items.VEGETABLES_BAMBOO_SHOOTS)
                .add(ModItems.PEELED_BAMBOO_SHOOTS.get());

        this.tag(ForgeTags.Items.VEGETABLES_BAMBOO_SPROUTS)
                .add(ModItems.PEELED_BAMBOO_SHOOTS.get());

        this.tag(ForgeTags.Items.VEGETABLES_LOTUS_ROOT)
                .add(ModItems.LOTUS_ROOT.get());

        this.tag(ForgeTags.Items.VEGETABLES_LOTUS_SEED)
                .add(ModItems.LOTUS_SEED.get());

        this.tag(ForgeTags.Items.VEGETABLES_LOTUS_NUT)
                .add(ModItems.LOTUS_SEED.get());

    }
}
